workspace.members = ["crates/*"]

[workspace.dependencies]
clap = "4.1.8"
tokio = { version = "1.26.0", features = ["full"] }
tonic = "0.8.3"
prost = "0.11.8"
tracing = "0.1"
tracing-subscriber = "0.3"
color-eyre = "0.6"
