apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: client
build:
  local:
    push: false
  artifacts:
    - image: tokio-example/client
      docker:
        dockerfile: Dockerfile
      requires:
        - image: tokio-example/base
          alias: BASE
    # - image: tokio-example/base
    #   docker:
    #     dockerfile: base.dockerfile
    #   context: ../..
manifests:
  rawYaml:
    - k8s/*
