apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: server
build:
  local:
    push: false
  artifacts:
    - image: tokio-example/server
      docker:
        dockerfile: Dockerfile
      requires:
        - image: tokio-example/base
          alias: BASE
manifests:
  rawYaml:
    - k8s/*
deploy:
  kubectl: {}